version: 0.2

runtime-versions:
  ruby: 2.6

env:
  parameter-store:
    PAAS_LOGIN_INTEGRATION: "/aws/reference/secretsmanager/epbr/govpaas/integration/PAAS_LOGINWRONG"
    PAAS_LOGIN_STAGING: "/aws/reference/secretsmanager/epbr/govpaas/staging/PAAS_LOGIN"
    PAAS_LOGIN_PRODUCTION: "/aws/reference/secretsmanager/epbr/govpaas/production/PAAS_LOGIN"

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install bundler:2.0.2
      - bundle install
      - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
      - echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - apt-get update
      - apt-get install cf-cli
  build:
    commands:
      - rake spec
      - echo $PAAS_LOGIN_INTEGRATION