version: 0.2

runtime-versions:
  ruby: 2.6

env:
phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install bundler:2.0.2
      - bundle install
  build:
    commands:
      - echo ">>>>>>>> RUNNING UNIT TESTS"
      - rake spec