version: 0.2

runtime-versions:
  ruby: 2.6

env:
  parameter-store:
    UNLEASH_URI: "epbr-unleash-integration-uri"
    STAGE: "epbr-govpaas-integration-space"
    DOCKER_POSTGRES_PASSWORD: "docker-postgres-password"

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install bundler:2.0.2
      - bundle install
      - docker run -d -p 5432:5432 --name postgres-test -e POSTGRES_PASSWORD=$DOCKER_POSTGRES_PASSWORD postgres:11
  pre_build:
    commands:
      - echo ">>>>>>>> Setting up the database"
      - rake db:create
      - rake db:migrate

  build:
    commands:
      - echo ">>>>>>>> RUNNING TESTS"
      - rake spec
