version: 0.2

runtime-versions:
  ruby: 2.6

env:
  parameter-store:
    PAAS_LOGIN_PRODUCTION: "epbr-govpaas-production-login"
    PAAS_PW_PRODUCTION: "epbr-govpaas-production-pw"
    STAGE: "epbr-govpaas-production-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    UNLEASH_URI: "epbr-unleash-production-uri"

phases:
  install:
    runtime-versions:
      ruby: 2.6
  pre_build:
    commands:
      - echo ">>>>>>>> DEPLOY TO PRODUCTION ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN_PRODUCTION -p "$PAAS_PW_PRODUCTION" -o $PAAS_ORG -s $STAGE
      - export DEPLOY_APPNAME="mhclg-epb-assessor-api-${STAGE}"

      - cf set-env "${DEPLOY_APPNAME}" UNLEASH_URI $UNLEASH_URI
      - cf set-env "${DEPLOY_APPNAME}" STAGE "${STAGE}"
  build:
    commands:
      - make generate-manifest

      - cf v3-apply-manifest -f manifest.yml

      - cf v3-zdt-push --no-start $DEPLOY_APPNAME
      - cf run-task $DEPLOY_APPNAME "rake db:migrate" --name migrate
  post_build:
    commands:
      - cf v3-start $DEPLOY_APPNAME
      - cf logout
