version: 0.2

runtime-versions:
  ruby: 2.6

env:
  parameter-store:
    PAAS_LOGIN_STAGING: "epbr-govpaas-staging-login"
    PAAS_PW_STAGING: "epbr-govpaas-staging-pw"
    PAAS_SPACE_STAGING: "epbr-govpaas-staging-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
      - echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - apt-get update
      - apt-get install cf-cli
  build:
    commands:
      - echo ">>>>>>>> DEPLOY TO INTEGRATION ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN_STAGING -p "$PAAS_PW_STAGING" -o $PAAS_ORG -s $PAAS_SPACE_STAGING
      - cf push mhclg-epb-assessor-api-staging
      - cf logout
