version: 0.2

runtime-versions:
  ruby: 2.6

env:
  parameter-store:
    PAAS_LOGIN_INTEGRATION: "epbr-govpaas-integration-login"
    PAAS_PW_INTEGRATION: "epbr-govpaas-integration-pw"
    PAAS_SPACE_INTEGRATION: "epbr-govpaas-integration-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - echo ">>>>>>>> READY TO DEPLOY"
  build:
    commands:
      - echo ">>>>>>>> DEPLOY TO INTEGRATION ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN_INTEGRATION -p "$PAAS_PW_INTEGRATION" -o $PAAS_ORG -s $PAAS_SPACE_INTEGRATION
      - cf push mhclg-epb-assessor-api-integration
      - cf logout
