openapi: "3.0.0"
info:
  title: Energy Performance of Buildings Register API
  description: API for all EPBR services (EPC, DEC, ACIR), maintained by the EPBR Service Team at MHCLG.
  version: "1.0"

servers:
  - url: https://mhclg-epb-assessor-api-integration.london.cloudapps.digital/api
    description: Integration server
  - url: https://mhclg-epb-assessor-api-staging.london.cloudapps.digital/api
    description: Staging server
tags:
  - name: Manage schemes
    description: Operations for managing schemes in the register
paths:
  /schemes:
    get:
      tags:
        - Manage schemes
      summary: Get a list of all energy assessment schemes in the register
      responses:
        200:
          description: List of all schemes
          content:
            application/json:
              schema:
                type: object
                properties:
                  schemes:
                    type: array
                    items:
                      $ref: '#/components/schemas/SchemeSummary'

    post:
      tags:
        - Manage schemes
      summary: Add a new energy assessment scheme to the register
      requestBody:
        description: The scheme to be added
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "EPCs 4 U"
      responses:
        201:
          description: Scheme succesfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchemeSummary'

        400:
          description: Scheme already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: "SCHEME_ALREADY_EXISTS"
                        title:
                          type: string
                          example: "A scheme with this name already exists in the register"

components:
  schemas:
    SchemeSummary:
      type: object
      properties:
        schemeId:
          type: string
          example: "432"
        name:
          type: string
          example: "EPBs 4 U"