development:
  adapter: postgresql
  database: epb_development
  host: 127.0.0.1
  username: postgres
  password: <%= ENV['DOCKER_POSTGRES_PASSWORD'] %>
test:
  adapter: postgresql
  database: epb_test
  username: postgres
  password: <%= ENV['DOCKER_POSTGRES_PASSWORD'] %>
  host: 127.0.0.1
production:
  database: epb
  url: <%= ENV['DATABASE_URL'] %>
