development:
  adapter: 'postgresql'
  database: 'epb_development'
integration:
  adapter: 'postgresql'
  database: 'epb_integration'
staging:
  adapter: 'postgresql'
  database: 'epb_staging'
production:
  adapter: 'postgresql'
  database: 'epb'