development:
  adapter: postgresql
  database: epb_development
  host: 127.0.0.1
  username: postgres
  password: <%= ENV['DOCKER_POSTGRES_PASSWORD'] %>
integration:
  adapter: postgresql
  database: epb_integration
staging:
  adapter: postgresql
  database: epb_staging
production:
  adapter: postgresql
  database: epb
