development:
  adapter: postgresql
  database: epb_development
  host: 127.0.0.1
  username: postgres
  password: <%= ENV['DOCKER_POSTGRES_PASSWORD'] %>
integration:
  database: epb_integration
  url: <%= ENV['DATABASE_URL'] %>
staging:
  database: epb_staging
  url: <%= ENV['DATABASE_URL'] %>
production:
  database: epb
  url: <%= ENV['DATABASE_URL'] %>
